repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
        exclude: ^docs/.*$
    -   id: flake8
        exclude: ^docs/.*$
    -   id: name-tests-test
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
        files: requirements-dev.txt
    -   id: pretty-format-json
        args:
        - --autofix
        - --indent=4
-   repo: git://github.com/asottile/reorder_python_imports
    rev: v1.6.1
    hooks:
    -   id: reorder-python-imports
        exclude: ^(docs/.*|setup.py)$
        args:
        - --add-import
        - from __future__ import absolute_import
        - --add-import
        - from __future__ import division
        - --add-import
        - from __future__ import print_function
        - --add-import
        - from __future__ import unicode_literals
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.22.1
    hooks:
    -   id: pyupgrade
-   repo: git://github.com/pre-commit/mirrors-autopep8
    rev: v1.3.1
    hooks:
    -   id: autopep8
        args:
        - -i
        - --ignore=E309,E501
        exclude: ^docs/.*$
