language: python

matrix:
  include:
  - python: "2.7"
    env: TOXENV=py27-default
  - python: "2.7"
    env: TOXENV=py27-simplejson
  - python: "3.5"
    env: TOXENV=py35-default
  - python: "3.6"
    env: TOXENV=py36-default
  - python: "3.6"
    env: TOXENV=pre-commit
  - python: "3.6"
    env: TOXENV=cover
  - python: "3.6"
    env: TOXENV=docs
install: pip install tox coveralls
script: tox
after_success: if [ "$TOXENV" == "cover" ]; then coveralls; fi
sudo: false
